public enum GameStatus
{
    PRESENTATION,
    NOT_STARTED,
    SHOTGUN_GRABBED,
    STARTING_GAME,
    
    IN_GAME,
    
    ALL_PUMPKINS_COLLECTED,
    CLOSE_THE_DOOR,
    AT_HOME_AFTER_OBJECTIVE,
    SLEEPING,

    PLAYER_DEAD,
    PUMKINS_STOLEN,
}